// All observations here are invented. No captured player data or fixture edits.
// Synthetic reports are generated by the shared battle model itself, so a test can
// state the true race pick and check that the inference never excludes it.
const battleModel = require('../../public/js/utils/battle-model');
const { inferBattleRace, VERSION, MODEL_NOT_BEFORE, KNOWN_SIDE_MAX_AGE_HOURS } = require('./battle-race-inference');

let pass = 0, fail = 0;
function ok(name, condition, detail) {
    if (condition) { pass++; console.log(`  ✅ ${name}`); }
    else { fail++; console.error(`  ❌ ${name}${detail === undefined ? '' : ` -> ${JSON.stringify(detail)}`}`); }
}
const ALL_PICKS = [-4, -3, -2, -1, 0, 1, 2, 3, 4];
const equal = (a, b) => JSON.stringify(a) === JSON.stringify(b);
const FIGHTING = battleModel.SHIPS.map(ship => ship.key);
const AUXILIARY = ['transports', 'colony_ships', 'starbases'];

const SUBJECT_ID = 11;
const ENEMY_ID = 22;
const BATTLE_AT = '2026-09-01T12:00:00Z';
// Our member: full intel recorded two hours before the battle.
const MEMBER = Object.freeze({
    has_intel: 1, race_attack: 0, race_defense: 0, physics: 10, mathematics: 12, level: 20,
    intel_updated_at: '2026-09-01 10:00:00',
});
const SUBJECT = Object.freeze({ science_level: 15, level: 20 });

function options(overrides = {}) {
    return {
        subject: SUBJECT,
        opponents: { [ENEMY_ID]: MEMBER },
        ...overrides,
    };
}

// Build a complete report row from the model's own survivors. `round` turns the model's
// fractional survivors into the whole ships a real report shows; it is called per type.
function synth({
    id = 101, role = 'att', subjectFleet = [1000, 0, 0], enemyFleet = [400, 0, 0], sbLevel = 0,
    rd = 0, math = 0, lvl = 20, ra = 0, phys = 0, enemy = MEMBER, round = Math.round,
    started_at = BATTLE_AT, cvIncludesStarbase = true, enemyId = ENEMY_ID,
} = {}) {
    const subjectStats = { ra, rd, phys, math, lvl };
    const enemyStats = {
        ra: enemy.race_attack, rd: enemy.race_defense, phys: enemy.physics, math: enemy.mathematics, lvl: enemy.level,
    };
    const atkFleet = role === 'att' ? subjectFleet : enemyFleet;
    const defFleet = role === 'att' ? enemyFleet : subjectFleet;
    const result = battleModel.simulate({
        atkFleet, defFleet, sbLevel,
        atk: role === 'att' ? subjectStats : enemyStats,
        def: role === 'att' ? enemyStats : subjectStats,
    });
    const row = {
        id, started_at, is_public: 1, winner: 'Synthetic winner',
        att_player_id: role === 'att' ? SUBJECT_ID : enemyId,
        def_player_id: role === 'att' ? enemyId : SUBJECT_ID,
        att_has_won: role === 'att' ? 1 : 0, def_has_won: role === 'att' ? 0 : 1,
    };
    const survivors = { att: result.survAtk, def: result.survDef };
    const fleets = { att: atkFleet, def: defFleet };
    for (const side of ['att', 'def']) {
        FIGHTING.forEach((ship, i) => {
            const alive = fleets[side][i] ? Math.max(0, Math.min(fleets[side][i], round(survivors[side][i]))) : 0;
            row[`${side}_${ship}`] = fleets[side][i];
            row[`${side}_${ship}_lost`] = fleets[side][i] - alive;
        });
        for (const ship of AUXILIARY) row[`${side}_${ship}`] = row[`${side}_${ship}_lost`] = 0;
    }
    const sbCv = battleModel.sbCV(sbLevel);
    if (sbLevel > 0) {
        row.def_starbases = 1;
        row.def_starbases_lost = result.survSB > 0 ? 0 : 1;
    }
    for (const side of ['att', 'def']) {
        const fleet = FIGHTING.map(ship => row[`${side}_${ship}`]);
        const lost = FIGHTING.map(ship => row[`${side}_${ship}_lost`]);
        const withStarbase = side === 'def' && sbLevel > 0 && cvIncludesStarbase;
        const starbaseLost = withStarbase ? sbCv - Math.round(result.survSB * sbCv) : 0;
        row[`${side}_combat_value`] = battleModel.cvOf(fleet) + (withStarbase ? sbCv : 0);
        row[`${side}_lost_cv`] = battleModel.cvOf(lost) + starbaseLost;
        row[`${side}_survived_cv`] = row[`${side}_combat_value`] - row[`${side}_lost_cv`];
    }
    return row;
}

const infer = (rows, opts = options()) => inferBattleRace(SUBJECT_ID, rows, opts);
function skipped(name, row, reason, opts) {
    const result = infer([row], opts);
    ok(name, result.skipped[reason] === 1 && result.eligible_report_count === 0
        && equal(result.defense.candidates, ALL_PICKS), result);
}
const narrowed = result => result.defense.candidates.length > 0 && result.defense.candidates.length < ALL_PICKS.length;

// Deterministic PRNG so the soundness sweep is reproducible.
function mulberry32(seed) {
    return function next() {
        seed |= 0; seed = seed + 0x6D2B79F5 | 0;
        let t = Math.imul(seed ^ seed >>> 15, 1 | seed);
        t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t;
        return ((t ^ t >>> 14) >>> 0) / 4294967296;
    };
}

console.log('── Result shape ──');
const basic = infer([synth({ rd: 0, math: 8 })]);
ok('the result declares conditional compatibility and supported race range',
    basic.version === VERSION && basic.assumptions.some(text => /not a probability/.test(text))
    && basic.assumptions.some(text => /supported -4 to \+4/.test(text)), basic);
ok('the version changes, so results saved by the one-sided method are not shown as current', VERSION === 2);
ok('ATK stays unresolved: the stored win_chance column is the dice roll',
    basic.attack.status === 'insufficient' && equal(basic.attack.candidates, ALL_PICKS)
    && /dice/.test(basic.attack.reason) && /#277/.test(basic.attack.reason), basic.attack);
ok('percent ranges describe race bonuses, not confidence probabilities',
    equal(basic.attack.bonus_percent_range, { min: -32, max: 32 }) && !('probability' in basic.defense));
ok('all results are JSON-safe', equal(JSON.parse(JSON.stringify(basic)), basic));

console.log('\n── Two-sided Defence from a known opponent and a science ceiling ──');
// The issue #282 table: four clean reports, the subject attacks and wins all four.
const TABLE_FLEETS = [
    [[1000, 0, 0], [400, 0, 0]],
    [[0, 300, 0], [1500, 0, 0]],
    [[800, 0, 0], [0, 40, 0]],
    [[2000, 0, 0], [900, 0, 0]],
];
const tableRows = (rd, math) => TABLE_FLEETS.map(([subjectFleet, enemyFleet], i) =>
    synth({ id: 201 + i, subjectFleet, enemyFleet, rd, math }));
let tableCells = 0;
let tableFailure = null;
for (const math of [0, 8, 15]) {
    for (const rd of [-4, -2, 0, 2, 4]) {
        const result = infer(tableRows(rd, math));
        tableCells++;
        if (!(result.defense.candidates.includes(rd) && narrowed(result) && result.eligible_report_count === 4)
            && !tableFailure) tableFailure = { rd, math, result };
    }
}
ok(`every one of the ${tableCells} table cells narrows DEF and keeps the true pick`, tableFailure === null, tableFailure);
const strong = infer(tableRows(4, 0));
ok('good survival now excludes low picks: DEF +4 gets a lower bound above -4',
    strong.defense.candidates[0] > -4 && strong.defense.candidates.includes(4), strong.defense);
const weakest = infer(tableRows(-4, 15));
ok('high losses still exclude high picks', weakest.defense.candidates.at(-1) < 4
    && weakest.defense.candidates.includes(-4), weakest.defense);
ok('a narrowed range is reported as compatible, not as a probability',
    strong.status === 'compatible' && strong.defense.status === 'compatible'
    && /both/.test(strong.defense.reason), strong.defense);

const defending = infer([synth({ role: 'def', subjectFleet: [1000, 0, 0], enemyFleet: [400, 0, 0], rd: 2, math: 8 })]);
ok('a defending winner uses its own losses and the attacker CV',
    defending.eligible_report_count === 1 && defending.defense.candidates.includes(2) && narrowed(defending), defending);

const lowCeiling = infer(tableRows(0, 3), options({ subject: { science_level: 3, level: 20 } }));
const highCeiling = infer(tableRows(0, 3), options({ subject: { science_level: 40, level: 20 } }));
ok('a lower science ceiling narrows DEF at least as much as a higher one',
    lowCeiling.defense.candidates.every(pick => highCeiling.defense.candidates.includes(pick))
    && lowCeiling.defense.candidates.includes(0) && highCeiling.defense.candidates.includes(0),
    { low: lowCeiling.defense.candidates, high: highCeiling.defense.candidates });

const mixedLevel = synth({ subjectFleet: [600, 60, 20], enemyFleet: [700, 0, 0], rd: 1, math: 5, lvl: 12 });
const mixedResult = infer([mixedLevel]);
ok('an all-three-types winner allows any player level up to the current one',
    mixedResult.eligible_report_count === 1 && mixedResult.defense.candidates.includes(1), mixedResult);

const conflict = infer([synth({ rd: -4, math: 0 }), synth({ id: 102, rd: 4, math: 15 })]);
ok('a model contradiction is reported without selecting a closest race',
    conflict.status === 'conflicting' && conflict.defense.status === 'conflicting'
    && conflict.defense.candidates.length === 0 && conflict.defense.bonus_percent_range === null, conflict);

console.log('\n── Known side ──');
skipped('a report without intel on the opponent has no known side', synth(), 'no_known_side',
    options({ opponents: {} }));
skipped('an opponent row without bio is not a known side', synth(), 'no_known_side',
    options({ opponents: { [ENEMY_ID]: { ...MEMBER, has_intel: 0 } } }));
skipped(`opponent intel older than ${KNOWN_SIDE_MAX_AGE_HOURS} h before the battle is too stale`, synth(), 'ally_stats_unknown',
    options({ opponents: { [ENEMY_ID]: { ...MEMBER, intel_updated_at: '2026-08-30 11:59:00' } } }));
skipped(`opponent intel more than ${KNOWN_SIDE_MAX_AGE_HOURS} h after the battle is too far away`, synth(), 'ally_stats_unknown',
    options({ opponents: { [ENEMY_ID]: { ...MEMBER, intel_updated_at: '2026-09-03 12:01:00' } } }));
skipped('opponent intel without a timestamp has no known age', synth(), 'ally_stats_unknown',
    options({ opponents: { [ENEMY_ID]: { ...MEMBER, intel_updated_at: null } } }));
ok('the result records how far the opponent intel was from the battle',
    basic.known_side_intel_max_age_hours === 2 && infer([]).known_side_intel_max_age_hours === null, basic);
ok('opponent intel just inside the window is used',
    infer([synth()], options({ opponents: { [ENEMY_ID]: { ...MEMBER, intel_updated_at: '2026-09-03 11:00:00' } } }))
        .eligible_report_count === 1);
const scouted = infer([synth({ rd: 1, math: 8, enemy: { ...MEMBER, race_attack: -2, physics: 18 } })],
    options({ opponents: { [ENEMY_ID]: { ...MEMBER, race_attack: -2, physics: 18 } } }));
ok('a scouted player outside our alliance counts as a known side like a member',
    scouted.eligible_report_count === 1 && scouted.defense.candidates.includes(1) && narrowed(scouted), scouted);
skipped('an unknown public science level is not treated as zero', synth(), 'science_level_unknown',
    options({ subject: { science_level: 0, level: 20 } }));
skipped('a missing public science level is not guessed', synth(), 'science_level_unknown',
    options({ subject: { level: 20 } }));
skipped('an all-three-types fleet needs the current player level as a ceiling',
    synth({ subjectFleet: [600, 60, 20], enemyFleet: [700, 0, 0] }), 'player_level_unknown',
    options({ subject: { science_level: 15 } }));
ok('a single-type fleet does not need the player level',
    infer([synth()], options({ subject: { science_level: 15 } })).eligible_report_count === 1);

console.log('\n── Starbases ──');
const sbDefence = infer([synth({ role: 'def', subjectFleet: [1000, 0, 0], enemyFleet: [500, 0, 0], sbLevel: 6, rd: 2, math: 8 })]);
ok('a defending winner with a starbase is eligible and keeps its true pick',
    sbDefence.eligible_report_count === 1 && sbDefence.defense.candidates.includes(2) && narrowed(sbDefence), sbDefence);
const sbFleetOnlyCv = infer([synth({ role: 'def', subjectFleet: [1000, 0, 0], enemyFleet: [500, 0, 0], sbLevel: 6,
    rd: 2, math: 8, cvIncludesStarbase: false })]);
ok('a defender with a starbase is eligible when the stored CV covers the fleet only',
    sbFleetOnlyCv.eligible_report_count === 1 && sbFleetOnlyCv.defense.candidates.includes(2), sbFleetOnlyCv);
const sbAttack = infer([synth({ subjectFleet: [1500, 0, 0], enemyFleet: [300, 0, 0], sbLevel: 7, rd: -1, math: 8 })]);
ok('an attacker against a starbase uses the level implied by the defender CV',
    sbAttack.eligible_report_count === 1 && sbAttack.defense.candidates.includes(-1) && narrowed(sbAttack), sbAttack);
skipped('an attacker against a starbase of unknown level is skipped',
    synth({ subjectFleet: [1500, 0, 0], enemyFleet: [300, 0, 0], sbLevel: 7, cvIncludesStarbase: false }),
    'starbase_level_unknown');
skipped('a starbase CV that matches no level is inconsistent',
    { ...synth({ subjectFleet: [1500, 0, 0], enemyFleet: [300, 0, 0], sbLevel: 7 }), def_combat_value: 900 + 63 },
    'inconsistent_combat_value');
skipped('an attacking starbase is not a real composition', { ...synth(), att_starbases: 1 }, 'unsupported_ship_composition');
skipped('civilian-fleet mechanics are excluded', { ...synth(), att_transports: 1 }, 'unsupported_ship_composition');
skipped('colony ships are excluded', { ...synth(), def_colony_ships: 2 }, 'unsupported_ship_composition');

console.log('\n── Eligibility and data-integrity gates ──');
const baseRow = synth({ rd: -4, math: 0 });
skipped('unpublished observations cannot be used as finalized losses', { ...baseRow, is_public: 0 }, 'unpublished_report');
skipped('a losing player does not inherit survivor-model bounds', {
    ...baseRow, att_has_won: 0, def_has_won: 1,
}, 'not_confirmed_winner');
skipped('contradictory winner flags are rejected', { ...baseRow, def_has_won: 1 }, 'not_confirmed_winner');
skipped('unknown winner flags are not treated as false', { ...baseRow, def_has_won: null }, 'not_confirmed_winner');
ok('free-text winner names are not mistaken for missing winner evidence',
    equal(infer([{ ...baseRow, winner: null }]).defense, infer([baseRow]).defense));
skipped('missing zero counts stay unknown', { ...baseRow, att_cruisers: null }, 'missing_ship_counts');
skipped('unknown auxiliary counts stay unknown', { ...baseRow, def_starbases: null }, 'missing_ship_counts');
skipped('negative initial counts are rejected', { ...baseRow, def_cruisers: -1 }, 'missing_ship_counts');
skipped('numeric strings are not coerced into evidence', { ...baseRow, att_destroyers: '1000' }, 'missing_ship_counts');
skipped('invalid report IDs cannot become stored evidence', { ...baseRow, id: null }, 'invalid_report_id');
skipped('the same player on both sides is ambiguous', { ...baseRow, def_player_id: SUBJECT_ID }, 'ambiguous_player_side');
skipped('a fleet with fewer than four ships is excluded',
    synth({ subjectFleet: [3, 0, 0], enemyFleet: [1, 0, 0] }), 'too_small_or_unopposed');
skipped('unopposed flights contain no battle evidence', { ...baseRow, def_destroyers: 0, def_destroyers_lost: 0,
    def_combat_value: 0, def_lost_cv: 0, def_survived_cv: 0 }, 'too_small_or_unopposed');
skipped('losses greater than initial ships are rejected', { ...baseRow, att_destroyers_lost: 1001 }, 'invalid_ship_losses');
skipped('missing loss counts stay unknown', { ...baseRow, att_destroyers_lost: null }, 'invalid_ship_losses');
skipped('annihilated winners do not establish a race malus', { ...baseRow, att_destroyers_lost: 1000,
    att_lost_cv: 3000, att_survived_cv: 0 }, 'annihilated_fleet');
skipped('zero losses are below rounding resolution', { ...baseRow, att_destroyers_lost: 0,
    att_lost_cv: 0, att_survived_cv: 3000 }, 'losses_below_rounding_resolution');
skipped('one ship lost does not support a precise multiplier', { ...baseRow, att_destroyers_lost: 1,
    att_lost_cv: 3, att_survived_cv: 2997 }, 'losses_below_rounding_resolution');
skipped('CV mismatches catch incomplete or shifted ship tables', { ...baseRow, def_combat_value: 1300 }, 'inconsistent_combat_value');
skipped('loss totals must agree with individual ship types', { ...baseRow, att_lost_cv: 123 }, 'inconsistent_loss_totals');
skipped('survivor totals must agree with individual ship types', { ...baseRow, att_survived_cv: null }, 'inconsistent_loss_totals');
const shifted = synth({ subjectFleet: [1000, 100, 0], enemyFleet: [900, 0, 0] });
skipped('incompatible per-type loss fractions cannot constrain a race', {
    ...shifted, att_cruisers_lost: 1, att_lost_cv: shifted.att_lost_cv - (shifted.att_cruisers_lost - 1) * 24,
    att_survived_cv: shifted.att_survived_cv + (shifted.att_cruisers_lost - 1) * 24,
}, 'inconsistent_loss_fractions');

console.log('\n── Version, identity and stable aggregation ──');
skipped('pre-v6 battles use different defence multipliers', synth({ started_at: '2026-08-27T23:59:59Z' }), 'unsupported_rules_date',
    options({ opponents: { [ENEMY_ID]: { ...MEMBER, intel_updated_at: '2026-08-27 22:00:00' } } }));
skipped('the unknown patch deployment time excludes the whole patch day', synth({ started_at: '2026-08-28T23:59:59Z' }),
    'unsupported_rules_date', options({ opponents: { [ENEMY_ID]: { ...MEMBER, intel_updated_at: '2026-08-28 22:00:00' } } }));
ok('the first unambiguous v6 UTC day is supported', infer([synth({ started_at: MODEL_NOT_BEFORE })],
    options({ opponents: { [ENEMY_ID]: { ...MEMBER, intel_updated_at: '2026-08-29 00:00:00' } } })).eligible_report_count === 1);
skipped('invalid battle dates never default to a current timestamp', synth({ started_at: 'yesterday' }), 'invalid_battle_date');
skipped('a missing battle timestamp is rejected', synth({ started_at: null }), 'invalid_battle_date');
skipped('impossible calendar dates do not silently roll into the next month', synth({ started_at: '2026-09-31T12:00:00Z' }), 'invalid_battle_date');
skipped('24-hour timestamps do not silently roll into the next day', synth({ started_at: '2026-09-01T24:00:00Z' }), 'invalid_battle_date');
skipped('offset-less ISO input is not interpreted in local time', synth({ started_at: '2026-09-01T12:00:00' }), 'invalid_battle_date');
skipped('reports before the current identity cutoff cannot infer a former race', synth(), 'before_current_player',
    options({ notBefore: '2026-09-02T00:00:00Z' }));
skipped('an invalid identity cutoff blocks inference', synth(), 'invalid_player_cutoff', options({ notBefore: 'unknown' }));
skipped('RedZone combat artefacts do not silently use standard rules', synth(), 'unsupported_ruleset', options({ universe: 'redzone' }));
ok('SQLite timestamps and explicit offsets identify the same encounter',
    equal(infer([synth({ started_at: '2026-09-01 12:00:00' })]), infer([synth({ started_at: '2026-09-01T14:00:00+02:00' })])));

const frozen = { ...synth({ rd: 1, math: 8 }), physics: 999, mathematics: 0, level: 999, race_defense: 4, has_intel: 1 };
const before = JSON.stringify(frozen);
Object.freeze(frozen);
ok('intel-shaped extra fields on a report row do not change inference',
    equal(infer([frozen]).defense, infer([synth({ rd: 1, math: 8 })]).defense));
ok('input report objects and bio-shaped fields are never mutated', JSON.stringify(frozen) === before);
const frozenOptions = options();
const optionsBefore = JSON.stringify(frozenOptions);
infer([synth()], frozenOptions);
ok('the supplied player stats are never mutated', JSON.stringify(frozenOptions) === optionsBefore);

const informative = [synth({ id: 103, rd: 0, math: 8 }), synth({ id: 102, subjectFleet: [0, 300, 0], enemyFleet: [1500, 0, 0], rd: 0, math: 8 })];
ok('evidence order does not change the assessment', equal(infer(informative), infer([...informative].reverse())));
const single = infer([informative[0]]);
const both = infer(informative);
ok('additional reports never widen the range',
    both.defense.candidates.every(pick => single.defense.candidates.includes(pick)) && both.defense.candidates.includes(0));
const duplicate = infer([synth(), synth()]);
ok('duplicate rows do not inflate evidence counts', duplicate.eligible_report_count === 1
    && duplicate.skipped.duplicate_report === 1 && equal(duplicate.used_report_ids, [101]));
const unrelated = infer([{ ...synth(), att_player_id: 99, def_player_id: 88 }]);
ok('player names and unrelated rows never substitute for player identity', unrelated.report_count === 0
    && unrelated.eligible_report_count === 0 && unrelated.status === 'insufficient');
ok('an empty history remains insufficient', infer([]).status === 'insufficient');

// Soundness: the subject's historical sciences and level are drawn anywhere under their
// public ceilings, the opponent's stats are whatever the intel says, and survivors are
// rounded either way. The true pick must never be excluded.
console.log('\n── Unknown historical stats cannot eliminate the true synthetic pick ──');
const random = mulberry32(282);
const pick = list => list[Math.floor(random() * list.length)];
const int = (lo, hi) => lo + Math.floor(random() * (hi - lo + 1));
const FLEETS = [[1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 1, 0], [1, 0, 1], [0, 1, 1], [1, 1, 1]];
let cases = 0;
let eligible = 0;
let narrowedCases = 0;
let counterexample = null;
for (let i = 0; i < 1500; i++) {
    const scienceLevel = int(1, 40);
    const levelCeiling = int(0, 40);
    const truth = { rd: pick(ALL_PICKS), math: int(0, scienceLevel), lvl: int(0, levelCeiling), ra: pick(ALL_PICKS), phys: int(0, scienceLevel) };
    const enemy = { ...MEMBER, race_attack: pick(ALL_PICKS), race_defense: pick(ALL_PICKS),
        physics: int(0, 40), mathematics: int(0, 40), level: int(0, 40) };
    const role = pick(['att', 'def']);
    const scale = int(50, 3000);
    const subjectFleet = pick(FLEETS).map(n => n * int(1, scale));
    const enemyFleet = pick(FLEETS).map(n => n * int(1, scale));
    const sbLevel = role === 'def' && random() < 0.3 ? int(1, 12) : 0;
    const rounding = pick([Math.floor, Math.ceil, Math.round, x => (random() < 0.5 ? Math.floor(x) : Math.ceil(x))]);
    const row = synth({ id: 1000 + i, role, subjectFleet, enemyFleet, sbLevel, enemy, round: rounding, ...truth });
    const result = infer([row], options({ subject: { science_level: scienceLevel, level: levelCeiling }, opponents: { [ENEMY_ID]: enemy } }));
    cases++;
    if (!result.eligible_report_count) continue;
    eligible++;
    if (narrowed(result)) narrowedCases++;
    if (!result.defense.candidates.includes(truth.rd) && !counterexample) {
        counterexample = { truth, enemy, role, subjectFleet, enemyFleet, sbLevel, scienceLevel, levelCeiling, candidates: result.defense.candidates };
    }
}
ok(`all ${eligible} eligible of ${cases} random synthetic battles preserve their true pick`, counterexample === null, counterexample);
ok('the sweep exercises a meaningful share of eligible reports', eligible > cases / 3, { eligible, cases });
ok('the sweep shows real narrowing, not only full ranges', narrowedCases > eligible / 2, { narrowedCases, eligible });

console.log(`\n${pass} passed, ${fail} failed`);
process.exitCode = fail ? 1 : 0;
